name: mimic
stages:
  - name: filter_codes
    params:
      codes_to_remove:
        - INFUSION_
        - SUBJECT_WEIGHT_AT_INFUSION
        - Weight
        - Height
        - eGFR
        - PROCEDURE//START
        - PROCEDURE//END
        - MEDICATION//START//
        - SUBJECT_FLUID_OUTPUT//
      is_prefix: true

  - name: preprocessing
    transforms:
      - DemographicData.retrieve_demographics_from_hosp_adm
      - DemographicData.process_race
      - DemographicData.process_marital_status
      - InpatientData.process_drg_codes
      - InpatientData.process_hospital_admissions
      - InpatientData.process_hospital_discharges
    vocab: ${vocab}

  - name: CodeCounter
    agg_to: ${output_dir}/${code_counts_fn}
    skip: ${is_not_null:${vocab}}

  - name: StaticDataCollector
    agg_to: ${output_dir}/static_data.pickle
    params:
      static_code_prefixes:
        - MEDS_BIRTH
        - GENDER
        - MARITAL
        - RACE

  - name: filter_codes
    params:
      codes_to_remove:
        - MEDS_BIRTH
        - GENDER
        - MARITAL
        - RACE
      is_prefix: true

  - name: inject_time_intervals
    params:
      time_intervals_spec: ${time_intervals_spec}

  - name: IntervalEstimator
    params:
      time_intervals_spec: ${time_intervals_spec}
    agg_to: ${output_dir}/${intervals_fn}
    skip: ${is_not_null:${vocab}}

  - name: CodeCounter
    agg_to: ${output_dir}/${code_counts_fn}
